# .project metadata for KubeFleet
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add adopters list (ADOPTERS.md)

schema_version: "1.0.0"
slug: "kubefleet"
name: "KubeFleet"
description: "A multi-cluster solution that enables users to effectively manage their applications running in multiple Kubernetes clusters."
type: "project"
project_lead: "michaelawyu"
slack_channels:
  - name: "#kubeFleet"
    link: "https://cloud-native.slack.com/"
    primary: true

maturity_log:
  - phase: "sandbox"
    date: "2025-01-21T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/307"

repositories:
  - "https://github.com/kubefleet-dev/kubefleet"

website: "https://kubefleet.dev/"

artwork: "https://landscape.cncf.io/logos/kubefleet.svg"

social:
  youtube: "https://www.youtube.com/@CNCFKubeFleet"

# TODO: Add ADOPTERS.md if your project tracks adopters
# adopters:
#   path: "https://github.com/kubefleet-dev/kubefleet/blob/main/ADOPTERS.md"


package_managers:
  docker:
    - "ghcr.io/kubefleet-dev/kubefleet/member-agent"
    - "ghcr.io/kubefleet-dev/kubefleet/refresh-token"
    - "ghcr.io/kubefleet-dev/kubefleet/hub-agent"
  helm:
    - "ghcr.io/kubefleet-dev/kubefleet/charts/hub-agent"
    - "ghcr.io/kubefleet-dev/kubefleet/charts/member-agent"

security:
  policy:
    path: "https://github.com/kubefleet-dev/kubefleet/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kubefleet-dev/kubefleet/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kubefleet-dev/kubefleet/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/kubefleet-dev/kubefleet/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kubefleet-dev/kubefleet/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kubefleet-dev/kubefleet/blob/main/README.md"

landscape:
  category: "Orchestration & Management"
  subcategory: "Scheduling & Orchestration"

# CLOMonitor Score: 75/100
# Documentation: 97 | License: 75 | Best Practices: 42 | Security: 68
